openapi: 3.0.0

info:
  description: API for the RUI backend
  version: '1.1.0'
  title: RUI
  contact:
    email: tobias.uhmann@gmail.com

tags:
  - name: symptom
    description: Everything about symptoms

paths:

  /taxonomy:

    get:
      tags:
        - symptoms
      summary: |
        Get the root symptoms, enriched by their child symptoms, which
        are in turn recursively enriched by their child symptoms.
      operationId: getTaxonomy
      responses:
        '200':
          description: Got taxonomy successfully
          content:
            applicatation/json:
              schema:
                type: object
                properties:
                  taxonomy:
                    type: array
                    items:
                      $ref: '#/components/schemas/DeepSymptom'

    put:
      tags:
        - symptoms
      summary: Overwrite the existing taxonomy
      operationId: putTaxonomy
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nodesTxt:
                  type: string
                  format: binary
                edgesTxt:
                  type: string
                  format: binary
                metaYml:
                  type: string
                  format: binary
      responses:
        '200':
          description: Put taxonomy successfully

  /symptom:

    post:
      tags:
        - symptoms
      summary: Create symptom
      operationId: postSymptom
      requestBody:
        $ref: '#/components/requestBodies/Symptom'
      responses:
        '201':
          description: Created symptom successfully

    put:
      tags:
        - symptoms
      summary: Create symptom
      operationId: putSymptom
      requestBody:
        $ref: '#/components/requestBodies/Symptom'
      responses:
        '200':
          description: Put symptom successfully

  '/symptom/{symptomId}':

    delete:
      tags:
        - symptoms
      summary: Delete symptom
      operationId: deleteSymptom
      parameters:
        - name: symptomId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Deleted symptom successfully

components:

  schemas:

    Symptom:
      type: object
      properties:
        id:
          type: integer
          format: int64
        parent:
          type: integer
          format: int64
        name:
          type: string
          example: Short circuit

    DeepSymptom:
      type: object
      properties:
        id:
          type: integer
          format: int64
        parent:
          type: integer
          format: int64
        names:
          type: array
          items:
            type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/DeepSymptom'

  requestBodies:

    Symptom:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Symptom'
