openapi: 3.0.0

info:
  description: API for the RUI backend
  version: 1.6.0
  title: RUI
  contact:
    email: tobias.uhmann@gmail.com

tags:
  - name: entities
  - name: matches
  - name: nodes
  - name: prediction
  - name: upload
    description: Upload initial taxonomy and matches

paths:

  /entities:

    post:
      tags:
        - entities
      operationId: postEntity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostEntity'
      responses:
        '201':
          description: Posted entity successfully

  /entities/{entityId}:

    delete:
      tags:
        - entities
      summary: Delete entity
      operationId: deleteEntity
      parameters:
        - name: entityId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted entity successfully

  /matches:

    get:
      tags:
        - matches
      summary: Get matches for an entity
      operationId: getMatches
      parameters:
        - in: query
          name: entity
          schema:
            type: integer
          description: Entity whose matches to get
        - in: query
          name: offset
          schema:
            type: integer
          description: Pagination Offset
        - in: query
          name: limit
          schema:
            type: integer
          description: Pagination Limit
      responses:
        '200':
          description: Got matches successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'

  /nodes:

    get:
      tags:
        - nodes
      summary: |
        Get the root nodes, enriched by their recursively enriched
        child nodes
      operationId: getNodes
      responses:
        '200':
          description: Got root nodes successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeepNode'

    post:
      tags:
        - nodes
      operationId: postNode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostNode'
      responses:
        '201':
          description: Posted node successfully

  /nodes/{nodeId}:

    patch:
      tags:
        - nodes
      summary: Patch node
      operationId: patchNode
      parameters:
        - name: nodeId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NodePatch'
      responses:
        '200':
          description: Patched node successfully

    delete:
      tags:
        - nodes
      summary: Delete node
      operationId: deleteNode
      parameters:
        - name: nodeId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted node successfully

  /nodes/{nodeId}/predictions:

    get:
      tags:
        - prediction
      summary: Get predictions for node
      operationId: getPredictions
      parameters:
        - name: nodeId
          in: path
          required: true
          schema:
            type: integer
        - in: query
          name: offset
          schema:
            type: integer
          description: Pagination Offset
        - in: query
          name: limit
          schema:
            type: integer
          description: Pagination Limit
      responses:
        '200':
          description: Got predictions successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CandidateWithPredictions'

  /predictions/{candidate}:

    patch:
      tags:
        - prediction
      summary: Dismiss prediction
      operationId: patchPrediction
      parameters:
        - name: candidate
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictionPatch'
      responses:
        '200':
          description: Prediction dismissed successfully

  /upload:

    put:
      tags:
        - upload
      summary: Put taxonomy and matches
      operationId: putUpload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Upload'
      responses:
        '200':
          description: Put taxonomy and matches successfully

components:
  schemas:

    # Entity

    Entity:
      description: Full entity
      type: object
      properties:
        id:
          type: integer
        nodeId:
          type: integer
        name:
          type: string
        matchesCount:
          type: integer

    PostEntity:
      description: Entity as posted individually (no ID)
      type: object
      properties:
        nodeId:
          type: integer
        name:
          type: string

    PostEntityNode:
      description: Entity as posted as part of a new node (no ID, no node)
      type: object
      properties:
        name:
          type: string

    # Match

    Match:
      description: Full match
      type: object
      properties:
        entityId:
          type: integer
        ticket:
          type: integer
        context:
          type: string
        mention:
          type: string
        mention_indexes:
          type: array
          items:
            type: integer

    # Node

    DeepNode:
      description: Full node plus recursively added children
      type: object
      properties:
        id:
          type: integer
        parentId:
          type: integer
        entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
        children:
          type: array
          items:
            $ref: '#/components/schemas/DeepNode'

    Node:
      description: Full node
      type: object
      properties:
        id:
          type: integer
        parentId:
          type: integer
        entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'

    NodePatch:
      properties:
        parentId:
          type: integer

    PostNode:
      description: Node as posted individually (no ID)
      type: object
      properties:
        parentId:
          type: integer
        entities:
          type: array
          items:
            $ref: '#/components/schemas/PostEntityNode'

    # Prediction

    CandidatePrediction:
      description: Prediction for a certain candidate
      type: object
      properties:
        score:
          type: number
        node:
          $ref: '#/components/schemas/Node'

    CandidateWithPredictions:
      description: Prediction about a node
      type: object
      properties:
        candidate:
          type: string
        dismissed:
          type: boolean
        parentPredictions:
          type: array
          items:
            $ref: '#/components/schemas/CandidatePrediction'
        synonymPredictions:
          type: array
          items:
            $ref: '#/components/schemas/CandidatePrediction'

    PredictionPatch:
      description: Dismiss a prediction
      type: object
      properties:
        dismissed:
          type: boolean

    PredictionResponse:
      description: Paginated predictions about node plus total number of predictions
      type: object
      properties:
        totalPredictions:
          type: integer
        predictions:
          $ref: '#/components/schemas/PredictionResponse'

    # Upload

    Upload:
      type: object
      properties:
        symptaxUploadZip:
          type: string
          format: binary
