openapi: 3.0.0

info:
  description: API for the RUI backend
  version: "1.0.0"
  title: RUI
  contact:
    email: tobias.uhmann@gmail.com

tags:
  - name: symptom
    description: Everything about symptoms

paths:

  /symptom:

    get:
      tags:
        - symptom
      summary: Get root symptoms
      operationId: getSymptom
      responses:
        '200':
          description: Got root symptoms successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Symptom'

    post:
      tags:
        - symptom
      summary: Create symptom
      operationId: postSymptom
      responses:
        '201':
          description: Created symptom
      requestBody:
        $ref: '#/components/requestBodies/Symptom'

  '/symptom/{symptomId}':

    delete:
      tags:
        - symptom
      summary: Delete symptom
      operationId: deleteSymptom
      parameters:
        - name: symptomId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Symptom not found

  '/taxonomy':

    put:
      tags:
        - symptom
      summary: Overwrite the existing taxonomy
      operationId: putTaxonomy
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nodesTxt:
                  type: string
                  format: binary
                edgesTxt:
                  type: string
                  format: binary
                metaYml:
                  type: string
                  format: binary
      responses:
        '200':
          description: Updated

components:

  schemas:

    Symptom:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Short circuit
        children:
          type: array
          items:
            $ref: '#/components/schemas/Symptom'

  requestBodies:

    Symptom:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Symptom'
