name: pipeline

on:
  push:

jobs:

  deliver_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key for git.ramlimit.de
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            xvlcw/rui-be:latest
            xvlcw/rui-be:0
            xvlcw/rui-be:0.14
            xvlcw/rui-be:0.14.0

