on: [ push ]

jobs:

  deliver_docker:
    runs-on: ubuntu-latest
    steps:

      - name: Add SSH key for git.ramlimit.de
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
